<template>
     <div class="w-10/12 sm:w-full p-4 pb-6 bg-quaternary pr-20" :style="{maskImage: `url('/background.svg')`, maskSize: 'cover'}">
        
        <SnippetResizable class="w-9/12 hover:bg-tertiary transition-all duration-500 mx-auto">
            <BasicInput 
            :resize="true" 
            style="filter: url(#outline-xs)"
            classNames="w-full text-md text-secondary leading-1 outline-none bg-transparent bg-opacity-20 placeholder-secondary sm:filter-none"
            placeholder="Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr dolor sit amet. Stet clita kasd gubergren, no sea takimata sanctus est."
            text="Unzählige Plattformen bieten im Internet vorgefertigte Templates für verschiedenste Einsatzbereiche an. Nähert man sich ihnen ohne Experimentierfreude und ohne die Bereitschaft, das gegebene option set zu hinterfragen, ist Vorsicht geboten. Denn schnell werden diese funktionalen Templates zu einem Symbol für ein Designverständnis, welches primär Effizienz- und Funktionalitätsansprüche bedient und der visuellen Auseinandersetzung mit Inhalten im Wege steht. Eine Erwiderung auf dieses inhärente Wertesystem funktionaler Templates könnte durch ihr antagonistisches Gegenstück erfolgen, genauer: durch dysfunktionale Templates. Im falschen Kontext erlangen funktionale Templates unbeschränkte Macht über Hierarchien visueller und inhaltlicher Elemente. Sie regieren mittels klarer Formen und Farben, die so wenig überraschen und polarisieren wie die Inhalte, die sie transportieren. Sie propagieren Lesbarkeit und vermeiden dabei panisch jeglichen Interpretationsspielraum. Dabei ori-entieren sich funktionale Templates stets an akzeptierten und etablierten Gestaltungsmustern. Statt diese zu hinterfragen, manifestieren Templates sie, da sich eine Beschränkung auf wenige, funktionale Designs als effizient erweist.  Ein dys funktionales Template kehrt diese Mechanismen um. Hierarchien werden auf den Kopf gestellt, Lesbarkeit und Eindeutigkeit mit Verwirrung und Widersprüchlichkeit beantwortet. Anstatt unter dem Diktat eines klaren Rasters zu reproduzieren, agiert das dysfunktionale Template dilettantisch, zufällig oder beliebig. Dort, wo funktionale Templates den Weg einfacher machen, macht das dysfunktionale Template ihn schwerer." />
        </SnippetResizable>

        <div class="space-x-3 flex wireframe-border p-4 mt-10 mx-20 items-center">
            <SnippetResizable v-for="i in 3" class="w-full h-48" />
        </div>
    </div>
</template>